/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F272_6272();
extern void F274_6434();
extern void F272_6276();
extern void F275_6438();
extern void F277_6602();
extern void F275_6443();
extern void F355_3952();
extern void F314_6118();
extern void F134_1666();
extern EIF_REFERENCE F134_1653();
extern EIF_BOOLEAN F134_1665();
extern EIF_BOOLEAN F134_1673();
extern void F134_1675();
extern void F134_1676();
extern void F134_1677();
extern void F75_1324();
extern EIF_TYPED_VALUE F75_1325();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F272_6272;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F272_6276;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F275_6438;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F275_6443;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F355_3952;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F274_6434;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F277_6602;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F314_6118;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F134_1666;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F134_1665;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F134_1653;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F134_1673;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F134_1675;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F134_1676;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F134_1677;

	egc_str_dtype = 273;

	egc_immstr8_dtype = 272;

	egc_str32_dtype = 276;

	egc_immstr32_dtype = 275;
	egc_arr_dtype = 354;
	egc_tup_dtype = 225;
	egc_disp_rout_id = 2295;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x01FA;
	egc_sp_wchar = 0x01E9;
	egc_sp_bool = 0x0290;
	egc_sp_uint8 = 0x020B;
	egc_sp_uint16 = 0x0363;
	egc_sp_uint32 = 0x027A;
	egc_sp_uint64 = 0x0177;
	egc_sp_int8 = 0x03B7;
	egc_sp_int16 = 0x0317;
	egc_sp_int32 = 0x01AF;
	egc_sp_int64 = 0x033F;
	egc_sp_real32 = 0x02C7;
	egc_sp_real64 = 0x02EB;
	egc_sp_pointer = 0x0265;
	egc_sp_ref = 0x0161;

	egc_uint8_dtype = 248;
	egc_uint16_dtype = 245;
	egc_uint32_dtype = 242;
	egc_uint64_dtype = 239;
	egc_int8_dtype = 236;
	egc_int16_dtype = 233;
	egc_int32_dtype = 230;
	egc_int64_dtype = 227;
	egc_bool_dtype = 263;
	egc_real32_dtype = 251;
	egc_char_dtype = 260;
	egc_wchar_dtype = 257;
	egc_real64_dtype = 254;
	egc_point_dtype = 266;

	egc_exception_dtype = 93;
	egc_except_emnger_dtype = 133;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_ucf";
	egc_system_location = "D:\\prod\\simple_ucf\\EIFGENs\\simple_ucf_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1765409504;
	egc_has_old_special_semantic = 0;
	scount = 999;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 797;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2866;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5350;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 74;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F75_1324;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F75_1325;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 33; /* APPLICATION */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 187; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 294; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
