/*
 * Code for class REFLECTOR_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F164_2284(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2285(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2286(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2287(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2288(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2289(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2290(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2291(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2292(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2293(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2294(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2295(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2296(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2297(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2298(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2299(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2300(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2301(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2302(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2303(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2304(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2305(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2306(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2307(EIF_REFERENCE);
extern EIF_TYPED_VALUE F164_2308(EIF_REFERENCE);
extern void EIF_Minit164(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {REFLECTOR_CONSTANTS}.none_type */
EIF_TYPED_VALUE F164_2284 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.pointer_type */
EIF_TYPED_VALUE F164_2285 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.reference_type */
EIF_TYPED_VALUE F164_2286 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.character_8_type */
EIF_TYPED_VALUE F164_2287 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.character_type */
EIF_TYPED_VALUE F164_2288 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.boolean_type */
EIF_TYPED_VALUE F164_2289 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_32_type */
EIF_TYPED_VALUE F164_2290 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_type */
EIF_TYPED_VALUE F164_2291 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.real_32_type */
EIF_TYPED_VALUE F164_2292 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.real_type */
EIF_TYPED_VALUE F164_2293 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.real_64_type */
EIF_TYPED_VALUE F164_2294 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.double_type */
EIF_TYPED_VALUE F164_2295 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.expanded_type */
EIF_TYPED_VALUE F164_2296 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.bit_type */
EIF_TYPED_VALUE F164_2297 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_8_type */
EIF_TYPED_VALUE F164_2298 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_16_type */
EIF_TYPED_VALUE F164_2299 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_64_type */
EIF_TYPED_VALUE F164_2300 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.character_32_type */
EIF_TYPED_VALUE F164_2301 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.wide_character_type */
EIF_TYPED_VALUE F164_2302 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_8_type */
EIF_TYPED_VALUE F164_2303 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_16_type */
EIF_TYPED_VALUE F164_2304 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_32_type */
EIF_TYPED_VALUE F164_2305 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_64_type */
EIF_TYPED_VALUE F164_2306 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.min_predefined_type */
EIF_TYPED_VALUE F164_2307 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.max_predefined_type */
EIF_TYPED_VALUE F164_2308 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

void EIF_Minit164 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
